#!/usr/bin/env bash
# Bash script that display information about the subdomains

dns_config() {
    domain="$1"
    subdomain="$2"
    record_type=$(dig +short -t CNAME "$subdomain.$domain" | grep -q '.' && echo "CNAME" || echo "A")
    destination=$(dig +short "$subdomain.$domain")

    if [ -n "$destination" ]; then
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    else
        echo "No record found for subdomain $subdomain"
    fi
}

if [ "$#" == 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        dns_config "$1" "$subdomain"
    done
elif [ "$#" == 2 ]; then
    dns_config "$1" "$2"
else
    echo "Usage: dns_config <domain> [subdomain]"
fi

