#!/usr/bin/env bash
# Installs and configures HAProxy

# Update package list and install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Backup the original HAProxy configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

# Define new HAProxy configuration
new_config="frontend front_lb
    bind *:80
    mode http
    default_backend back_lb

backend back_lb
    balance roundrobin
    server 529416-web-01 3.94.211.7:80 check
    server 529416-web-02 54.159.0.78:80 check"

# Replace the existing frontend and backend configurations
sudo sed -i '/frontend front_lb/,$d' /etc/haproxy/haproxy.cfg
echo -e "$new_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy to start on boot
echo -e "\nENABLED=1" | sudo tee /etc/default/haproxy

# Restart HAProxy service to apply changes
sudo service haproxy restart

# Verify HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg && echo "HAProxy configuration is valid."
