#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

hr=0
mins=1
while [ $hr -le 12 ]
do
    echo "Hour: $hr"
    while [ $mins -le 59 ]
    do
        echo "$mins"
        mins=$((mins + 1))
    done

mins=1
hr=$((hr + 1))

done